---
apiVersion: v2
name: linkwarden
description: A Helm chart for [Linkwarden](https://linkwarden.app/)
type: application
version: 0.1.18
appVersion: "v2.13.1"

dependencies:
  - name: meilisearch
    version: 0.17.2
    repository: https://meilisearch.github.io/meilisearch-kubernetes
