---
apiVersion: v2
name: linkwarden
description: A Helm chart for [Linkwarden](https://linkwarden.app/)
type: application
version: 0.1.27
appVersion: "v2.13.5"

dependencies:
  - name: meilisearch
    version: 0.24.1
    repository: https://meilisearch.github.io/meilisearch-kubernetes
