---
apiVersion: v2
name: linkwarden
description: A Helm chart for [Linkwarden](https://linkwarden.app/)
type: application
version: 0.1.21
appVersion: "v2.13.4"

dependencies:
  - name: meilisearch
    version: 0.19.0
    repository: https://meilisearch.github.io/meilisearch-kubernetes
